replicaCount: 2

image:
  repository: marcosmlima/mimoso
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: true
  annotations: {}

  name: "mimoso-app"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: localhost
      paths:
        - path: /mimoso(/|$)(.*)
          pathType: Prefix

  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
